app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/**
 * Protect incoming CSRF attacks from ajax requests
 *
 * @return 	void
 */
Route::filter('ajax', 'AJAXFilter');

/**
 * Homepage
 * @link /*
 */
Route::get('/', array(
	'as' => 'home',
	'uses' => 'HomeController@getIndex'
));

/**
 * Item Routes
 * @link item/*
 */
Route::resource('item', 'ItemController');

/**
 * User Routes
 * @link user/*
 */
Route::resource('user', 'UserController');

/**
 * Review Routes
 * @link review/*
 */
Route::resource('review', 'ReviewController');

/**
 * Transaction Messages Routes
 * @link transaction/*
 */
Route::resource('transaction', 'TransactionController');

/**
 * Message & Conversation Routes
 * @link message/
 * @link conversation/*
 */
Route::resource('message', 'MessageController');
Route::resource('conversation', 'ConversationController');

/**
 * Debugging Route
 */
Route::get('debug', (array('as' => 'debug', function()
{
	$tags = Item::byTag('iphone');
	var_dump($tags);
})));

/**
 * Tag Routes
 * @link tag/{tag}
 */
Route::get('tag/{tag}', 'TagController@getIndex');

/**
 * Query Searching Routes
 * @link search/*
 */
Route::get('api/search', 'SearchController@getIndex');

/**
 * AJAX Routes
 * @link ajax/
 */
Route::controller('ajax', 'AJAXController');

/**
 * Account Panel Routes
 * @link settings/
 */
Route::controller('settings', 'SettingsController');

/**
 * Authentication Routes
 * @link /(auth*)
 */
Route::controller('/', 'AuthenticationController');

/**
 * Dashboard Routes
 * @link dashboard/
 */
Route::controller('dashboard', 'DashboardController');

app/models/Message.php
<?php

use Carbon\Carbon;

class Message extends Eloquent {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'messages';

	/**
	 * Columns fillable by the model
	 *
	 * @var string
	 */
	protected $fillable = array(
		'user_id',
		'conversation_id',
		'body',
		'user_hide',
		'recepient_hide',
		'created_at',
		'updated_at'
	);

	/**
	 * Return the user's correspondent with the conversation
	 *
	 * @return 	mixed
	 */
	public function correspondent()
	{
		return ($this->user_id == Auth::user()->id)
			? User::where('id', '=', $this->recepient_id)->first()
			: User::where('id', '=', $this->user_id)->first();
	}

	/**
	 * Returns a [Carbon]-ized string of given time
	 *
	 * @return 	string
	 */
	public function timeAgo()
	{
		$date = new Carbon($this->created_at);
		return $date->diffForHumans();
	}

	/**
	 * ORM with the messages table
	 *
	 * @return 	mixed
	 */
	public function conversation()
	{
		return $this->belongsTo('Conversation');
	}

	/**
	 * ORM with the users table
	 *
	 * @return mixed
	 */
	public function user()
	{
		return $this->belongsTo('User');
	}

}

app/controllers/MessageController.php
<?php

class MessageController extends BaseController {

	/**
	 * Initial configurations for all instance of this controller
	 *
	 * @return 	void
	 */
	public function __construct()
	{
		$this->beforeFilter('auth', array('only' => array('index', 'create', 'store', 'delete')));
	}

	/**
	 * Display a listing of the resource
	 *
	 * @return 	Response
	 */
	public function index()
	{
		//
	}

	/**
	 * Create a new instance of the resource
	 *
	 * @return 	Response
	 */
	public function create()
	{
		// Compose a message
	}

	/**
	 * Store the created resource to the database
	 *
	 * @return 	Response
	 */
	public function store()
	{
		// Validate
		$user = Auth::user();

		// Fetch & INIT
		$cid = Input::get('conversation_id');
		$conversation = Conversation::find($cid);

		// Update the conversation
		$conversation->updated_at = new DateTime;
		$conversation->recepient_hide = false;
		$conversation->user_hide = false;
		if(User::isRecepientAt($cid)) {
			$conversation->recepient_read = false;
		} else {
			$conversation->user_read = false;
		}


		// Create a new message from the passed input
		$message = new Message(array(
			'user_id'			=>	$user->id,
			'conversation_id'	=>	$cid,
			'body'				=>	Input::get('body'),
			'created_at'		=>	new DateTime,
			'updated_at'		=>	new DateTime,
		));

		if($message->save() && $conversation->save()) {
			Session::flash('success', 'Your message has been sent');
			return Redirect::route('conversation.show', $conversation->id);
		}

		Session::flash('error', 'An error has occured!');
		return Redirect::route('conversation.show', $conversation->id);
	}

	/**
	 * Show the specified resource
	 *
	 * @param 	int 		$id
	 * @return 	Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Edit the specified resource
	 *
	 * @param 	int 		$id
	 * @return 	Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource
	 *
	 * @param 	int 		$id
	 * @return 	Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Delete the specified resource
	 *
	 * @param 	int 		$id
	 * @return 	Response
	 */
	public function destroy($id)
	{
		//
	}
}

app/views/messages/index.blade.php
@extends('templates/master')

@section('title')
	- Messages
@stop

@section('style')
	<style>
		tr.clickable_row:hover {
			cursor: pointer;
		}

		.grey {
			color: gray;
		}

		.grey:hover {
			color: black;
			text-decoration: none;
		}
	</style>
@stop

@section('content')
	<div class="row">

		{{-- Sidebar --}}
		<div class="col-md-3">
			<div class="list-group">
				<a href="#" class="list-group-item active">
					<span class="glyphicon glyphicon-envelope"></span> Inbox
					@if(Conversation::countUnread())
						<span class="badge"> {{ Conversation::countUnread() }} </span>
					@endif
				</a>
				<a href="#" class="list-group-item" data-toggle="modal" data-target="#new-conversation">
					<span class="glyphicon glyphicon-pencil"></span> New Conversation
				</a>
			</div>

			<div class="list-group">
				<a href="#" class="list-group-item">
					<span class="glyphicon glyphicon-cog"></span> Settings
				</a>
			</div>
		</div>

		<div class="col-md-9">
			<div class="panel panel-default">
				<div class="panel-heading">
					<strong>
						Inbox
						@if(!empty($conversations) && Conversation::countUnread())
							<span class="badge"> {{ Conversation::countUnread() }} </span>
						@endif
					</strong>
				</div>
				@if(count($conversations) < 1)
					<div class="panel-body">
						<div class="alert alert-info">
							You have <em>no messages</em>.
							<a href="{{ URL::route('conversation.create') }}" class="alert-link">Send a <em>private</em> message</a> to another user!
						</div>
					</div>
				@else
					<table class="table table-hover">
						<thead>
							<tr>
								<td> <span class="glyphicon glyphicon-user"></span> </td>
								<td> <span class="glyphicon glyphicon-comment"></span> </td>
								<td> <span class="glyphicon glyphicon-calendar"></span> </td>
								<td> </td>
							</tr>
						</thead>
						<tbody>
							@foreach($conversations as $conversation)
								<tr class="clickable_row  @if(!$conversation->read()) active @endif" href="{{ $conversation->id }}">
									<td> {{ $conversation->correspondent()->username }} </td>
									<td> {{ $conversation->preview() }}</td>	
									<td> {{ $conversation->lastInteraction() }} </td>
									<td>
										<a id="conversation-read" href="http://" class="grey" data-id="{{ $conversation->id }}">
											@if($conversation->read())
													<span class="glyphicon glyphicon-eye-close"></span>
											@else
												<span class="glyphicon glyphicon-eye-open"></span>
											@endif
										</a>
										<a href="#" class="grey">
											<span class="glyphicon glyphicon-remove"></span>
										</a>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
				@endif
			</div>
		</div>

	</div>
@stop

@section('modals')
	@include('templates/modals.new-conversation')
@stop

@section('scripts')
	<script>
		$(function() {
			$('.clickable_row').on('click', function() {
				console.log("gay");
				$this = $(this);
				window.location.replace("{{ URL::to('conversation') }}/" + $this.attr('href'));
			});

			$('a#conversation-read').on('click', function(e) {
				e.preventDefault();

				$.ajax({
					url: "{{ url('conversation/') }}" + data(id),
					type: 'DELETE',
					dataType: 'json',
					success: function(data) {
						if(data.status) {
							window.location.reload();
						}
					}
				});
			});
		});
	</script>
@stop

app/views/messages/show.blade.php
@extends('templates/master')

@section('title')
	- {{ $conversation->correspondent()->username }}
@stop

@section('content')
	<div class="row">

		{{-- Sidebar --}}
		<div class="col-md-3">
			<div class="list-group">
				<a href="{{ URL::route('conversation.index') }}" class="list-group-item">
					<span class="glyphicon glyphicon-envelope"></span> Inbox
					@if(Conversation::countUnread())
						<span class="badge"> {{ Conversation::countUnread() }} </span>
					@endif
				</a>
				<a href="#" class="list-group-item" data-toggle="modal" data-target="#new-conversation">
					<span class="glyphicon glyphicon-pencil"></span> New Conversation
				</a>
			</div>

			<div class="list-group">
				<a href="#" class="list-group-item">
					<span class="glyphicon glyphicon-cog"></span> Settings
				</a>
			</div>
		</div>

		<div class="col-md-9">
			<div class="clearfix">
				<h4> {{ $conversation->correspondent()->username }}
					<div class="pull-right">
						<div class="btn-group">
							<button type="button" class="btn btn-default btn-xs">
								<span class="glyphicon glyphicon-cog"></span>
								 Actions
							</button>
							<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
								<span class="caret"></span>
							    <span class="sr-only">Toggle Dropdown</span>
							</button>
							<ul class="dropdown-menu" role="menu">
								<li>
									<a href="#">
										@if($conversation->read())
											<span class="glyphicon glyphicon-eye-close"></span> Mark as Read
										@else
											<span class="glyphicon glyphicon-eye-open"></span> Mark as Unread
										@endif
									</a>
								</li>
								<li class="divider"></li>
								<li>
									<a href="#">
										<span class="glyphicon glyphicon-minus-sign"></span> Block Conversation
									</a>
								</li>
								<li>
									<a href="#">
										<span class="glyphicon glyphicon-remove"></span> Delete Conversation
									</a>
								</li>
							</ul>
						</div>
					</div>
				</h4>
			</div>
			<hr>
			@foreach($messages as $message)
				<div class="well">
					<div class="row">
						<div class="col-md-1">
							<h5 class="text-center">								
								<img class="img-circle" src="{{ $message->user->profile->avatar() }}" width="48" height="48" />
							</h5>
						</div>

						<div class="col-md-10">
							<h5>
								<strong> {{ $message->user->username }} </strong> <br />
								<small> <span class="glyphicon glyphicon-comment"></span> {{ $message->timeAgo() }} </small>
							</h5>
							{{{ $message->body }}}
						</div>

						<div class="col-md-1">
							<h5 class="text-right">
								<small> <span class="glyphicon glyphicon-chevron-down"></span> </small>								
							</h5>
						</div>
					</div>
				</div>
			@endforeach
			<hr>
			<div class="row">
			{{ Form::open(array('route' => 'message.store')) }}
				{{ Form::token() }}
				{{ Form::hidden('conversation_id', $conversation->id) }}
				<div class="col-md-11">
					{{ Form::textarea('body', Input::old('body'), array('class' => 'form-control', 'rows' => '1')) }}
				</div>

				<div class="col-md-1">
					{{ Form::submit('Send', array('class' => 'btn btn-info')) }}
				</div>
			{{ Form::close() }}
			</div>
		</div>
	</div>
	<br />
@stop

@section('modals')
	@include('templates/modals.new-conversation')
@stop