app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/**
 * Protect incoming CSRF attacks from ajax requests
 *
 * @return 	void
 */
Route::filter('ajax', 'AJAXFilter');

/**
 * Homepage
 * @link /*
 */
Route::get('/', array(
	'as' => 'home',
	'uses' => 'HomeController@getIndex'
));

/**
 * Item Routes
 * @link item/*
 */
Route::resource('item', 'ItemController');

/**
 * User Routes
 * @link user/*
 */
Route::resource('user', 'UserController');

/**
 * Review Routes
 * @link review/*
 */
Route::resource('review', 'ReviewController');

/**
 * Transaction Messages Routes
 * @link transaction/*
 */
Route::resource('transaction', 'TransactionController');

/**
 * Message & Conversation Routes
 * @link message/
 * @link conversation/*
 */
Route::resource('message', 'MessageController');
Route::resource('conversation', 'ConversationController');

/**
 * Debugging Route
 */
Route::get('debug', (array('as' => 'debug', function()
{
	$tags = Item::byTag('iphone');
	var_dump($tags);
})));

/**
 * Tag Routes
 * @link tag/{tag}
 */
Route::get('tag/{tag}', 'TagController@getIndex');

/**
 * Query Searching Routes
 * @link search/*
 */
Route::get('api/search', 'SearchController@getIndex');

/**
 * AJAX Routes
 * @link ajax/
 */
Route::controller('ajax', 'AJAXController');

/**
 * Account Panel Routes
 * @link settings/
 */
Route::controller('settings', 'SettingsController');

/**
 * Authentication Routes
 * @link /(auth*)
 */
Route::controller('/', 'AuthenticationController');

/**
 * Dashboard Routes
 * @link dashboard/
 */
Route::controller('dashboard', 'DashboardController');

app/views/index.blade.php
@extends('templates.master')

@section('title')
	- Available items
@stop

@section('style')
	<style>
		.thumbnail h1,
		.thumbnail h2,
		.thumbnail h3,
		.thumbnail h4,
		.thumbnail h5,
		.thumbnail h6,
		.thumbnail small {
			margin: 0.25em 0.5em 1em 0.5em;
		}

		p.caption {
			font-size: 0.9em;
			margin-left: 0.05em;
			height: 130px;
		}
	</style>
@stop

@section('content')
	@include('templates.alerts')
	<div class="rows">
		<div class="col-md-3">
			<div class="list-group">
				<a href="#" class="list-group-item"> All items </a>
				<a href="#" class="list-group-item"> All items </a>
				<a href="#" class="list-group-item"> All items </a>
				<a href="#" class="list-group-item"> All items </a>
			</div>
		</div>

		<div class="col-md-9">
			<div class="clearfix">
				<h4>
					<a href="{{ URL::route('item.create') }}" class="btn btn-info pull-right">
						<span class="glyphicon glyphicon-pushpin"></span>
						Sell Your Item Online
					</a>
				</h4>

				<h3> Latest Items </h3>
			</div>

			<hr>

			<div class="row">
				@foreach($items as $item)
					<div class="col-md-4">
						<div class="thumbnail">
							<img src="{{ $item->cover()->link() }}" width="396" height="120"/>

							<div class="clearfix">
								<h4 class="pull-right"> <small> {{ $item->currency->symbol }} </small> {{{ $item->price }}} </h4>
								<h4> <a href="{{ URL::route('item.show', $item->id) }}"> {{{ $item->name }}} </a>
								</h4>
							</div>

							<p class="caption"> {{ $item->short_description }} </p>
							<br />
							<div class="clearfix">
								<h6 class="pull-right">
									<small> {{ $item->timeAgo() }} </small>
								</h6>
								<h6> <a href="{{ URL::route('user.show', $item->user->id) }}"> {{{ $item->user->username }}} </a> </h6>
							</div>
						</div>
					</div>
				@endforeach
			</div>

			{{ $items->links() }}
		</div>
	</div>
@stop